import {
  Mic,
  Brain,
  Activity,
  Target,
} from "lucide-react";

import "../styles/about.css";

function About() {
  return (
    <div className="about-page">

      {/* HERO */}

      <section className="about-hero">

        <div className="about-container">

          <div className="about-hero-logo">
            <img src="/logo.png" alt="Vaani AI" className="about-hero-logo-img" />
          </div>

          <h1>
            Building Trust in
            <span> Digital Voices</span>
          </h1>

          <p>
            Vaani AI is an intelligent voice analysis platform designed
            to help identify whether an audio recording is generated by a
            human or artificial intelligence.
          </p>

        </div>

      </section>


      {/* MISSION */}

      <section className="mission-section">

        <div className="about-container">

          <div className="section-heading">

            <h2>Our Mission</h2>

            <p>
              As AI-generated voices become increasingly realistic,
              distinguishing between authentic human speech and synthetic
              audio is becoming more important than ever.
            </p>

          </div>


          <div className="mission-grid">

            <div className="mission-card">

              <div className="mission-icon">
                <img src="/logo.png" alt="Vaani AI" className="mission-logo" />
              </div>

              <h3>Detect Deepfakes</h3>

              <p>
                Identify potentially AI-generated or manipulated voice
                recordings using intelligent audio analysis.
              </p>

            </div>


            <div className="mission-card">

              <div className="mission-icon">
                <Brain size={30} />
              </div>

              <h3>AI Powered Analysis</h3>

              <p>
                Analyze important speech characteristics such as spectral
                patterns, pauses and micro-variations.
              </p>

            </div>


            <div className="mission-card">

              <div className="mission-icon">
                <Target size={30} />
              </div>

              <h3>Fast & Practical</h3>

              <p>
                Get quick analysis results through audio upload or
                real-time voice detection.
              </p>

            </div>

          </div>

        </div>

      </section>


      {/* HOW IT WORKS */}

      <section className="how-section">

        <div className="about-container">

          <div className="section-heading">

            <h2>How Vaani AI Works</h2>

            <p>
              A simple pipeline for analyzing spoken audio.
            </p>

          </div>


          <div className="timeline">


            <div className="timeline-item">

              <div className="timeline-number">
                01
              </div>

              <div className="timeline-content">

                <Mic size={24} />

                <h3>Audio Input</h3>

                <p>
                  Upload an audio recording or use live voice detection
                  through your microphone.
                </p>

              </div>

            </div>


            <div className="timeline-item">

              <div className="timeline-number">
                02
              </div>

              <div className="timeline-content">

                <Activity size={24} />

                <h3>Feature Extraction</h3>

                <p>
                  The system analyzes important acoustic features from
                  the audio signal.
                </p>

              </div>

            </div>


            <div className="timeline-item">

              <div className="timeline-number">
                03
              </div>

              <div className="timeline-content">

                <Brain size={24} />

                <h3>AI Classification</h3>

                <p>
                  The trained model evaluates the extracted features and
                  predicts whether the voice is Human or AI-generated.
                </p>

              </div>

            </div>


            <div className="timeline-item">

              <div className="timeline-number">
                04
              </div>

              <div className="timeline-content">

                <img src="/logo.png" alt="Vaani AI" className="timeline-logo" />

                <h3>Result & Confidence</h3>

                <p>
                  Receive a prediction along with a confidence score and
                  detailed feature analysis.
                </p>

              </div>

            </div>

          </div>

        </div>

      </section>


      {/* TECHNOLOGY */}

      <section className="technology-section">

        <div className="about-container">

          <div className="section-heading">

            <h2>Built With Modern Technology</h2>

            <p>
              Vaani AI combines modern web development and
              machine learning technologies.
            </p>

          </div>


          <div className="tech-grid">

            <div className="tech-card">

              <h3>React</h3>

              <p>
                Modern and responsive frontend interface.
              </p>

            </div>


            <div className="tech-card">

              <h3>FastAPI</h3>

              <p>
                High-performance backend API for audio processing.
              </p>

            </div>


            <div className="tech-card">

              <h3>TensorFlow</h3>

              <p>
                Machine learning model for voice classification.
              </p>

            </div>


            <div className="tech-card">

              <h3>WebSockets</h3>

              <p>
                Real-time communication for live voice analysis.
              </p>

            </div>

          </div>

        </div>

      </section>


      {/* CTA */}

      <section className="about-cta">

        <div className="about-container">

          <div className="cta-box">

            <div>

              <h2>
                Ready to Analyze a Voice?
              </h2>

              <p>
                Upload an audio file and let Vaani AI analyze it.
              </p>

            </div>

            <a
              href="/detect"
              className="about-cta-btn"
            >
              Start Detection
            </a>

          </div>

        </div>

      </section>

    </div>
  );
}

export default About;